# Sheets: Founder, Bloodline, Exporer

# Configure Rolls
rollFormula = "2d6"

# Define roll result ranges.
[rollResults]
  [rollResults.failure]
    range = "6-"
    label = "Complications..."
  [rollResults.partial]
    range = "7-9"
    label = "Partial success."
  [rollResults.success]
    range = "10+"
    label = "Success!"

######################################
## Exporers ##########################
######################################
# Define the Exporer (Character) group.
[character]
# TODO add Context [Refuge, Drive, Breach] & Looks to Descritpion tab

    # Define stats.
    [character.stats]
        iron = "Iron"
        glass = "Glass"
        sulphur = "Sulphur"
        mercury = "Mercury"

    # Define attributes.
    [character.attributesTop]
 
        [character.attributesTop.harm]
            type = "Clock"
            label = "Harm"
            description = "Choose to take 1 wound instead of 1 harm"
            max = 5
            default = 0
        
        [character.attributesTop.contamination]
            type = "Clock"
            label = "Contamination"
            description = "When all are marked raise Blood & clear Contamination"
            max = 3
            default = 0

        [character.attributesTop.blood]
            type = "Number"
            label = "Blood"
            description = "When Blood increases, take a blood advance"
            default = 0

    # Define sidebar details.
    [character.attributesLeft]

        [character.attributesLeft.wounds]
            type = "ListMany"
            label = "Wounds"
            description = "Take 1 wound instead of 1 harm."
            options = [
                "Minor Wound",
                "Major Wound",
                "Deadly Wound"
            ]

        [character.attributesLeft.bloodAdv]
            type = "ListMany"
            label = "Blood Advances"
            description = ""
            options = [
                "Get +1 to a stat (max 3)|2",
                "Get a Blood Gift|2"
            ]

    # Define groups for moves.
    [character.moveTypes]
        playbook = "Playbook Moves"
        blood = "Blood Gifts"
        exploration = "Exploration Moves"
        confrontation = "Confrontation Moves"
        covenants = "Covenant Moves"
        bloodline = "Bloodline Moves"

    # Define groups for equipment.
    [character.equipmentTypes]
        armor = "Armor"
        gear = "Gear"
        covenants = "Covenants"

######################################
## Founders ##########################
######################################
# Define the Founder group.
[founder]
# TODO add Context [Refuge, Drive, Breach] & Looks to Descritpion tab
    baseType = 'character' 

    # Define stats.
    [founder.stats]
        iron = "Iron"
        glass = "Glass"
        sulphur = "Sulphur"
        mercury = "Mercury"

    # Define attributes.
    # [founder.attributesTop]

    # Define sidebar details.
    [founder.attributesLeft]
        [founder.attributesLeft.harm]
            type = "Clock"
            label = "Harm"
            max = 5
            default = 0
    
        [founder.attributesLeft.contamination]
            type = "Clock"
            label = "Contamination"
            description = "When all are marked raise Blood & clear Contamination"
            max = 3
            default = 0

        [founder.attributesLeft.blood]
            type = "Number"
            label = "Blood"
            default = 0

    # Define groups for moves.
    [founder.moveTypes]
        exploration = "Exploration Moves"
        confrontation = "Confrontation Moves"
        covenants = "Covenant Moves"
        bloodline = "Bloodline Moves"

    # Define groups for equipment.
    [founder.equipmentTypes]
        weapons = "Weapons"

######################################
## Bloodlines ########################
######################################
# Define the Bloodline group.
[bloodline]
    baseType = 'character'
    
    # Define stats.
    [bloodline.stats]
        chalices = "Chalices"
        swords = "Swords"
        relics = "Relics"
        wands = "Wands"
        coins = "Coins"

    # Define attributes.
    # [bloodline.attributesTop]

    # Define sidebar details.
    [bloodline.attributesLeft]
        [bloodline.attributesLeft.style]
            type = "LongText"
            label = "Style"
        
        [bloodline.attributesLeft.lore]
            type = "LongText"
            label = "Lore"

    # Define groups for moves.
    [bloodline.moveTypes]
        bloodline = "Bloodline Moves"
        generations = "The Passing of Generations"

    # Define groups for equipment.
    [bloodline.equipmentTypes]
        pacts = "Pacts"

######################################
## NPCS: Minions #####################
######################################
[npc]
    # Define attributes.
    # [npc.attributesTop]

    [npc.attributesLeft]

        [npc.attributesLeft.type]
            type = "ListMany"
            label = "Type"
            options = [
                "Minion",
                "Significant Foe"
            ]
        [npc.attributesLeft.description]
            type = "LongText"
            label = "Description"

        # Define logical groups for moves.
        [npc.moveTypes]
            reactions = "Reactions"
